#!/data/data/com.termux/files/usr/bin/bash
# if source $HOME/SakiSP-NEXT/local/Android/Android_function; then
# 	echo -e "${SUSSEC}加载安卓功能成功"
# 	log "加载安卓功能成功"
# else
# 	echo -e "${WORRY}加载安卓功能失败"
# 	log "加载安卓功能失败"
# fi
for script in $HOME/SakiSP-NEXT/local/Android/function/* ; do
	source "$script" 
	log "加载:$script"
done
case $1 in
install)
	case $2 in
	proot)
		log "安装proot容器"
		install_proot
		;;
	*)
		echo -e "\n$WORRY请输入完整命令\ninstall proot"
		;;
	esac

	;;
start)
	case $2 in
	proot)
		log "启动proot容器"
		start_proot
		;;
	*)
		echo -e "\n$WORRY请输入完整命令\nstart proot"
		;;
	esac

	;;
*)
	Android_menu=$(
		whiptail --title "SakiSP-NEXT V8.2.1" --menu "请选择功能" 15 60 8 \
			"1" "🍀 管理proot容器" \
			"2" "🤓 垃圾清理" \
			"3" "🐸 Android软件商店（尝鲜）" \
			"4" "🗑 卸载脚本" \
			"0" "🌚 退出" \
			"D" "⛳️ debuger"  3>&1 1>&2 2>&3
	)
	case $Android_menu in
	1)
		log "管理proot容器"
		open_proot=$(
			whiptail --title "选择功能" --menu "请按自己的需求来" 15 60 4 \
				"1" "安装proot容器" \
				"2" "启动proot容器" \
				"3" "删除proot容器" \
				"0" "退出" 3>&1 1>&2 2>&3
		)
		case $open_proot in
		1)
			log "安装proot容器"
			install_proot
			;;
		2)
			log "启动proot容器"
			start_proot
			;;
		3)
			log "删除proot容器"
			rm_proot
			;;
		*)
			log "退出"
			echo -e "${RED}QUIT$RES"
			;;
		esac
		;;
	2)
		log "垃圾清理"
		garbage_collection
		;;
	3)
		log "Android软件商店"
		android_store
		;;	
	4)
		log "卸载脚本"
		uninstall_sakispnext
		;;			
	D)
		debuger
		;;
	esac
	;;
esac
